# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wzmrfUdGAUOk2HICtku3l3VHgcBNsw0T
"""

import json
from datetime import datetime,time

x = '''[{
  "StudentID": 1867,
  "Gate": "Gate-2",
  "Time": "08::34::12"
},
{
  "StudentID": 1867,
  "Gate": "Gate-1",
  "Time": "12::27::53"
},
 {
  "StudentID": 1867,
  "Gate": "Gate-1",
  "Time": "13::36::19"
},
 {
  "StudentID": 1867,
  "Gate": "Gate-2",
  "Time": "17::14::12"
}]'''

StudentJSON = json.loads(x)
time_str = []
i =0
length = len(StudentJSON)
print(length)
if(length%2 != 0):
  raise TypeError("Out Time is not Specified")
else :
    # Storing all time in list for easy manipulation
  for i in range(0,length):
      time_str.append(StudentJSON[i]["Time"])
      print(time_str[i])

  # Converting Time String to Time
  for i in range(0,length):
    time_str[i] = datetime.strptime(time_str[i], '%H::%M::%S').time()

  #Converting Time object to dateTime
  date = datetime(1, 1, 2)
  time_Student_in = time_str[0];
  time_Student_out = time_str[length-1];
  time1 = datetime.combine(date, time_Student_in)

  time2 = datetime.combine(date, time_Student_out)

  # FIRST QUESTION :::: TOTAL TIME
  Total_Time = time2 - time1
  print("Total Time is = ", Total_Time)


  # SECOND QUESTION QUESTION :::: AVERAGE TIME
  AVG = '0::0::0'
  SUM = '0::0::0'
  AVG_T = datetime.strptime(AVG,'%H::%M::%S').time() 
  sum_t = datetime.strptime(SUM,'%H::%M::%S').time()
  AVG_TIME  = datetime.combine(date, AVG_T)
  SUM_TIME = datetime.combine(date, sum)

  for i in range(0,length,2):
    time1 = datetime.combine(date, time_str[i])
    time2 = datetime.combine(date, time_str[i+1])
    SUM_TIME = time2 - time1
    AVG_TIME = AVG_TIME + SUM_TIME
  AVERAGET = AVG_TIME.time()
  print("AVERAGE TIME IS = " , AVERAGET)